sowa/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from numpy import r_, array
from statsmodels.api import tsa
from wtforms import StringField, SubmitField, FileField, IntegerField, FloatField, TextAreaField, BooleanField, \
    SelectField
from wtforms.validators import NumberRange, InputRequired, Regexp, ValidationError
from sowa.posts.utils import is_stationary, is_invertible


class DatasetForm(FlaskForm):
    """
    The form used to generate a custom ARMA dataset.
    """
    ar_params = StringField('AR parameters', validators=[
        Regexp(r'(^$|^(?:[+-]?\d+(?:\.\d*)?|\.\d+)(?:,(?:[+-]?\d+(?:\.\d*)?|\.\d+))*$)',
               message='Invalid input. Insert all coefficients separated by a comma (e.g. \"0.3,0.001\")')])
    ma_params = StringField('MA parameters', validators=[
        Regexp(r'(^$|^(?:[+-]?\d+(?:\.\d*)?|\.\d+)(?:,(?:[+-]?\d+(?:\.\d*)?|\.\d+))*$)',
               message='Invalid input. Insert all coefficients separated by a comma (e.g. \"0.3,0.001\")')])
    t_max = IntegerField('Number of samples', validators=[InputRequired(), NumberRange(min=100, max=10000)],
                         default=200)
    variance = FloatField('Variance', validators=[InputRequired(), NumberRange(min=0)], default=1)
    try:
        seed = IntegerField('Random seed', validators=[InputRequired(), NumberRange(min=0, max=4294967295)],
                            default=12345)  # TODO fix OverflowError for large inputs
    except OverflowError as e:
        raise Exception(e.args[0])
    submit = SubmitField('Create dataset')

    def validate_ar_params(self, ar_params):
        try:
            ar_params_array = array(ar_params.data.split(",")).astype(float)
        except:
            ar_params_array = array([])
        if not is_stationary(ar_params_array):
            raise ValidationError('The parameters selected generate a non-stationary process. Select other parameters.')
        # ar = r_[1, -ar_params_array]  # add zero-lag and negate
        # arma_process = tsa.ArmaProcess(ar=ar)
        # if not arma_process.isstationary:
        #     raise ValidationError('The parameters selected generate a non-stationary process. Select other parameters.')

    def validate_ma_params(self, ma_params):
        try:
            ma_params_array = array(ma_params.data.split(",")).astype(float)
        except:
            ma_params_array = array([])
        ma = r_[1, ma_params_array]  # add zero-lag
        arma_process = tsa.ArmaProcess(ma=ma)
        if not arma_process.isinvertible:
            raise ValidationError('The parameters selected generate a non-invertible process. Select other parameters.')

    def validate(self, extra_validators=None):
        """Custom validator to ensure at least on of the parameter fields is used."""
        if super().validate(extra_validators):
            if not (self.ar_params.data or self.ma_params.data):
                self.ar_params.errors.append('At least one of these fields must have a value.')
                self.ma_params.errors.append('At least one of these fields must have a value.')
                return False
            else:
                return True
        return False


class EvaluateEstimationsForm(FlaskForm):
    """
    The form used to evaluate the performances of the parameter estimation tool.
    """
    ar_params = StringField('AR parameters', validators=[
        Regexp(r'(^$|^(?:[+-]?\d+(?:\.\d*)?|\.\d+)(?:,(?:[+-]?\d+(?:\.\d*)?|\.\d+))*$)',
               message='Invalid input. Insert all coefficients separated by a comma (e.g. \"0.3,0.001\")')])
    ma_params = StringField('MA parameters', validators=[
        Regexp(r'(^$|^(?:[+-]?\d+(?:\.\d*)?|\.\d+)(?:,(?:[+-]?\d+(?:\.\d*)?|\.\d+))*$)',
               message='Invalid input. Insert all coefficients separated by a comma (e.g. \"0.3,0.001\")')])
    t_max = IntegerField('Number of samples', validators=[InputRequired(), NumberRange(min=100, max=10000)],
                         default=200)
    library = SelectField(label='Library', choices=[('sm', 'Statsmodels (recommended)'), ('cm', 'Experimental')])
    n = IntegerField('Number of tests', validators=[InputRequired(), NumberRange(min=10, max=100)], default=30)

    variance = FloatField('Variance', validators=[InputRequired(), NumberRange(min=0)], default=1)
    submit = SubmitField('Evaluate')

    def validate_ar_params(self, ar_params):
        try:
            ar_params_array = array(ar_params.data.split(",")).astype(float)
        except:
            ar_params_array = array([])
        if not is_stationary(ar_params_array):
            raise ValidationError('The parameters selected generate a non-stationary process. Select other parameters.')

        # ar = r_[1, -ar_params_array]  # add zero-lag and negate
        # arma_process = tsa.ArmaProcess(ar=ar)
        # if not arma_process.isstationary:
        #     raise ValidationError('The parameters selected generate a non-stationary process. Select other parameters.')

    def validate_ma_params(self, ma_params):
        try:
            ma_params_array = array(ma_params.data.split(",")).astype(float)
        except:
            ma_params_array = array([])
        if not is_invertible(ma_params_array):
            raise ValidationError('The parameters selected generate a non-invertible process. Select other parameters.')
        # ma = r_[1, ma_params_array]  # add zero-lag
        # arma_process = tsa.ArmaProcess(ma=ma)
        # if not arma_process.isinvertible:
        #     raise ValidationError('The parameters selected generate a non-invertible process. Select other parameters.')

    def validate(self, extra_validators=None):
        """Custom validator to ensure at least on of the parameter fields is used."""
        if super().validate(extra_validators):
            if not (self.ar_params.data or self.ma_params.data):
                self.ar_params.errors.append('At least one of these fields must have a value.')
                self.ma_params.errors.append('At least one of these fields must have a value.')
                return False
            else:
                return True
        return False


class AnalysisForm(FlaskForm):
    """
    The form used to perform a parameter estimation on a given dataset.
    """
    dataset = FileField('Upload Dataset', validators=[InputRequired(), FileAllowed(['csv'])])
    p = IntegerField('p', validators=[InputRequired(), NumberRange(min=0)], default=0)
    q = IntegerField('q', validators=[InputRequired(), NumberRange(min=0)], default=0)
    is_private = BooleanField('Private')
    title = StringField('Title', validators=[])
    description = TextAreaField('Description')
    library = SelectField(label='Library', choices=[('sm', 'Statsmodels (recommended)'), ('cm', 'Experimental')])
    submit = SubmitField('Run')

    def validate(self, extra_validators=None):
        """Custom validator to ensure at least on of the parameter fields is used."""
        if super().validate(extra_validators):
            if self.p.data == 0 and self.q.data == 0:
                self.p.errors.append('Those fields cannot be 0 at the same time')
                self.q.errors.append('Those fields cannot be 0 at the same time')
                return False
            else:
                return True
        return False

sowa/posts/controller.py
from secrets import token_hex

from flask import flash, abort
from flask_login import current_user
from numpy import array, float, savetxt

from sowa.posts.utils import simulate_arma_data, evaluate_fitting
from sowa import db
from sowa.models import Post
from sowa.config import Config


def delete_post_controller(post_id):
    post = Post.query.get_or_404(post_id)  # If it doesn't exist: error 404
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return None


def generate_dataset_controller(form):
    # Parse the input
    try:
        ar_params_array = array(form.ar_params.data.split(",")).astype(float)
    except:
        ar_params_array = array([])
    try:
        ma_params_array = array(form.ma_params.data.split(",")).astype(float)
    except:
        ma_params_array = array([])
    sim_data, p, q = simulate_arma_data(form.t_max.data, ar_params_array, ma_params_array,
                                        form.seed.data, form.variance.data)
    filename = token_hex(8)  # Generate a new filename
    savetxt(Config.DATASETS_FOLDER + filename + ".csv", sim_data, delimiter=",")
    return filename


def estimations_evaluator_controller(form):
    # Parse the input
    try:
        ar_params_array = array(form.ar_params.data.split(",")).astype(float)
    except:
        ar_params_array = array([])
    try:
        ma_params_array = array(form.ma_params.data.split(",")).astype(float)
    except:
        ma_params_array = array([])
    return evaluate_fitting(form.t_max.data, ar_params_array, ma_params_array, form.variance.data, form.n.data, form.library.data)

sowa/posts/routes.py
from secrets import token_hex
from flask import Blueprint, send_file, abort, flash
from flask import render_template, url_for, redirect
from flask_login import current_user, login_required

import concurrent.futures

from sowa.models import Post
from sowa.posts.forms import DatasetForm, AnalysisForm, EvaluateEstimationsForm
from sowa.posts.controller import delete_post_controller, generate_dataset_controller, estimations_evaluator_controller
from sowa.config import Config
from sowa.posts.utils import execute_analysis

posts = Blueprint('posts', __name__)


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)  # If it doesn't exist: error 404
    if post.is_private and post.author != current_user:
        abort(403)
    return render_template('posts/post.html', title=post.id, post=post)


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    delete_post_controller(post_id)
    return redirect(url_for('main.history'))


@posts.route("/dataset", methods=['GET', 'POST'])
@login_required
def generate_dataset():
    form = DatasetForm()
    if form.validate_on_submit():
        dataset_fn = generate_dataset_controller(form)
        return redirect(url_for('posts.download_dataset', filename=dataset_fn))
    return render_template('posts/dataset_generator.html', title='Create ARMA Dataset', form=form,
                           legend='Create ARMA Dataset')


@posts.route("/download-dataset/<string:filename>/")
@login_required
def download_dataset(filename):
    """
    Download a newly generated dataset.
    :param filename:    The name of the csv file to download. (without extension)
    :return:
    """
    return send_file('static/datasets/' + filename + '.csv', as_attachment=True)  # , attachment_filename=filename)


@posts.route("/estimation", methods=['GET', 'POST'])
@login_required
def estimate_parameters():
    form = AnalysisForm()
    if form.validate_on_submit():
        print(current_user)
        filename = token_hex(8) + '.csv'  # Generate a new filename
        form.dataset.data.save(Config.DATASETS_FOLDER + filename)
        # with concurrent.futures.ThreadPoolExecutor() as executor:
        #     executor.submit(child_job, form.p.data, form.q.data, filename, form.title.data,
        #                     form.description.data, form.is_private.data, current_user.username, form.library.data)
        # flash("Your request has been processed. Check your posts again.", category='success')
        post = execute_analysis(p=form.p.data, q=form.q.data, library=form.library.data, title=form.title.data,
                         description=form.description.data, is_private=form.is_private.data, filename=filename)
        return redirect(url_for('posts.post', post_id=post.id))
    # thread = threading.Thread(target=execute_analysis, args=[form, filename])
    # thread.start()
    # post = execute_analysis(form, filename)
    return render_template('posts/analyser.html', title='New Analysis', form=form, legend='New Analysis')


@posts.route("/fitting-evaluator", methods=['GET', 'POST'])
@login_required
def estimations_evaluator():
    form = EvaluateEstimationsForm()
    if form.validate_on_submit():
        plot_fn = estimations_evaluator_controller(form)
        return render_template('posts/estimations_evaluator.html', title='Evaluate Estimations', form=form,
                               legend='Evaluate Estimations', plot_fn=plot_fn)
    return render_template('posts/estimations_evaluator.html', title='Evaluate Estimations', form=form,
                           legend='Evaluate Estimations')

sowa/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import not_, and_

from sowa import db, bcrypt
from sowa.users.controller import register_user_controller
from sowa.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from sowa.models import User, Post
from sowa.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = register_user_controller(form)
        flash(f'Account created for {user.username}! You are now able to log in', category='success')
        return redirect(url_for('users.login'))
    return render_template("users/register.html", title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Log in unsuccessful. Please check email and password', category='danger')
    return render_template("users/login.html", title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)  # Save uploaded file
            current_user.image_file = picture_file  # Set the profile picture
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', category='success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("users/account.html", title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', default=1, type=int)
    user = User.query.filter_by(username=username).first_or_404()  # Get the relative user
    if current_user == user:
        query = Post.query.filter_by(author=user)
    else:
        query = Post.query.filter(and_(Post.author == user, not_(Post.is_private)))
    posts = query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page)
    return render_template("posts/user_posts.html", posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:  # Make sure the user is not logged in
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template("users/reset_request.html", title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:  # Make sure the user is not logged in
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', category='warning')
        return redirect(url_for(reset_request))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to login', category='success')
        return redirect(url_for('users.login'))
    return render_template("users/reset_token.html", title='Reset Password', form=form)

sowa/templates/posts/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2"
                   href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %H:%M') }} (UTC)</small>
                <div>
                    <button class="btn btn-info btn-sm m-1 dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Export Data
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{{ url_for('posts.download_dataset', filename=post.id) }}">Original
                            Dataset (.csv)</a>
                        <a class="dropdown-item disabled" href="#">Analysis (.pdf)</a>
                        <a class="dropdown-item disabled" href="#">Analysis (.tex)</a>
                    </div>
                    {% if post.author == current_user %}
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
                                data-target="#deleteModal">Delete
                        </button>
                    {% endif %}
                    <!-- Private / Public flag-->
                    {% if post.is_private %}
                        <span class="text-muted float-right mr-3">Private <i class="fa fa-lock"></i></span>
                    {% else %}
                        <span class="text-muted float-right mr-3">Public <i class="fa fa-unlock"></i></span>
                    {% endif %}
                </div>
            </div>
            <!-- Title -->
            {% if post.title %}
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">
                    {{ post.title }}
                </a></h2>
            {% else %}
                <!-- Display default title -->
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">
                    ARMA({{ post.p }}, {{ post.q }}) analysis
                </a></h2>
            {% endif %}
            <!-- Description -->
            {% if post.description %}
                <legend class="border-bottom mb-4">Description</legend>
                <p class="article-content">{{ post.description }}</p>
            {% endif %}
            <!-- Estimation -->
            <legend class="border-bottom mb-4">Estimation of parameters</legend>
            <p class="article-content">The user identified the given dataset as an ARMA({{ post.p }}, {{ post.q }}).
                We know that the process fulfills the following equation</p>
            <p style="text-align:center">\( Y_t = \)
                {% for i in range(1, post.p + 1) %}
                    \( \phi_{ {{ i }} } Y_{t- {{ i }} } + \)
                {% endfor %}
                \( U_t \)
                {% for j in range(1, post.q + 1) %}
                    \( + \theta_{ {{ j }} } U_{t- {{ j }} } \)
                {% endfor %}\(\,.\)</p>
            <p> The parameter estimation yields the following parameters</p>
            <p style="text-align:center">
                {% for i in range(1, post.p + post.q + 1) %}
                    {% if i < post.p + 1 %}
                        \( \phi_ {{ i }} =  {{ post.result.split(',')[i - 1] }} \)
                    {% else %}
                        \( \theta_ {{ i - post.p }} =  {{ post.result.split(',')[i - 1] }} \)
                    {% endif %}
                    {% if i != post.p + post.q %}
                        ,
                    {% endif %}
                {% endfor %}\(\,.\)
            </p>
            <p>The estimated variance of the residuals is</p>
            <p style="text-align:center">
                $$ \sigma^2 = {{ post.sigma2 }} \,.$$
            </p>
            <p>The standard error is is</p>
            <p style="text-align:center">
                $$ SE = {{ post.stderr }} \,.$$
            </p>
            <!-- Plots -->
            <legend class="border-bottom mb-4">Plots</legend>
            In this section are displayed several plots useful for the dataset analysis.
            <!-- Dataset plot -->
            <div class="thumbnail">
                <a href="/static/plots/{{ post.id }}.png">
                    <img src="/static/plots/{{ post.id }}.png" alt="Plot" style="width:100%">
                </a>
            </div>
            <!-- PACF plot -->
            <div class="thumbnail">
                <a href="/static/plots/{{ post.id }}-pacf.png">
                    <img src="/static/plots/{{ post.id }}-pacf.png" alt="Plot" style="width:100%">
                </a>
            </div>
            <!-- ACF plot -->
            <div class="thumbnail">
                <a href="/static/plots/{{ post.id }}-acf.png">
                    <img src="/static/plots/{{ post.id }}-acf.png" alt="Plot" style="width:100%">
                </a>
            </div>
        </div>
        <img class="rounded-circle article-img"
             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    </article>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

sowa/templates/posts/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Post by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img"
                 src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2"
                       href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %H:%M') }} (UTC)</small>
                    <!-- Private / Public flag-->
                    {% if post.is_private %}
                        <span class="text-muted float-right mr-3">Private <i class="fa fa-lock"></i></span>
                    {% else %}
                        <span class="text-muted float-right mr-3">Public <i class="fa fa-unlock"></i></span>
                    {% endif %}
                </div>
                <!-- Title -->
                {% if post.title %}
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">
                        {{ post.title }}
                    </a></h2>
                {% else %} <!-- Display default title -->
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">
                        ARMA({{ post.p }}, {{ post.q }}) estimation
                    </a></h2>
                {% endif %}
                <p class="article-content">Parameter estimation for an ARMA({{ post.p }}, {{ post.q }}) time series.

                    (<a href="{{ url_for('posts.post', post_id=post.id) }}">Read more</a>)</p>
                <div class="thumbnail">
                    <a href="/static/plots/{{ post.id }}.png">
                        <img src="/static/plots/{{ post.id }}.png" alt="Plot" style="width:100%">
                    </a>
                </div>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4"
                   href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4"
                   href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}