sowa/main/routes.py
from flask import Blueprint
from flask import render_template, request
from flask_login import current_user
from sqlalchemy import or_, not_

from sowa.models import Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    """
    Homepage of the website.
    :return:
    """
    return render_template("main/home.html", title='Homepage', legend='Homepage Sowa')


@main.route("/history")
def history():
    page = request.args.get('page', default=1, type=int)
    # Take all public posts + private posts of the current_user (if authenticated)
    if current_user.is_authenticated:
        query = Post.query.filter(or_(Post.author == current_user, not_(Post.is_private)))
    else:
        query = Post.query.filter(not_(Post.is_private))
    posts = query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page)
    return render_template("main/history.html", posts=posts)

sowa/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import not_, and_

from sowa import db, bcrypt
from sowa.users.controller import register_user_controller
from sowa.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from sowa.models import User, Post
from sowa.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = register_user_controller(form)
        flash(f'Account created for {user.username}! You are now able to log in', category='success')
        return redirect(url_for('users.login'))
    return render_template("users/register.html", title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Log in unsuccessful. Please check email and password', category='danger')
    return render_template("users/login.html", title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)  # Save uploaded file
            current_user.image_file = picture_file  # Set the profile picture
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', category='success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template("users/account.html", title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', default=1, type=int)
    user = User.query.filter_by(username=username).first_or_404()  # Get the relative user
    if current_user == user:
        query = Post.query.filter_by(author=user)
    else:
        query = Post.query.filter(and_(Post.author == user, not_(Post.is_private)))
    posts = query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page)
    return render_template("posts/user_posts.html", posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:  # Make sure the user is not logged in
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template("users/reset_request.html", title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:  # Make sure the user is not logged in
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', category='warning')
        return redirect(url_for(reset_request))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to login', category='success')
        return redirect(url_for('users.login'))
    return render_template("users/reset_token.html", title='Reset Password', form=form)

sowa/templates/main/history.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img"
                 src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2"
                       href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %H:%M') }} (UTC)</small>
                    <!-- Private / Public flag-->
                    {% if post.is_private %}
                        <span class="text-muted float-right mr-3">Private <i class="fa fa-lock"></i></span>
                    {% else %}
                        <span class="text-muted float-right mr-3">Public <i class="fa fa-unlock"></i></span>
                    {% endif %}
                </div>
                <!-- Title -->
                {% if post.title %}
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">
                        {{ post.title }}
                    </a></h2>
                {% else %}
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">
                        ARMA({{ post.p }}, {{ post.q }}) estimation
                    </a></h2>
                {% endif %}
                <p class="article-content">Parameter estimation for an ARMA({{ post.p }}, {{ post.q }}) time series.

                    (<a href="{{ url_for('posts.post', post_id=post.id) }}">Read more</a>)</p>
                <div class="thumbnail">
                    <a href="/static/plots/{{ post.id }}.png">
                        <img src="/static/plots/{{ post.id }}.png" alt="Plot" style="width:100%">
                    </a>
                </div>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.history', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4"
                   href="{{ url_for('main.history', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

sowa/templates/main/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <legend class="border-bottom mb-4">Homepage</legend>
        <p><b>SOWA</b> (<i>Stochastic Optimizer Web Application</i>) is a Web application for <b>time series parameter
            estimation</b> written in Python with the Flask framework. The estimations are performed making use of <b>Kalman
            Filter</b> and <b>Maximum-Likelihood Estimation</b>.
            <br><br>
            This website has been created by Roberto Pizziol in the scope of his MSc thesis «<i>Parameter Estimation
                Methods for Stochastic Models of Time Series</i>» at the University of Rome Tor Vergata.
        </p>
    </div>
    <div class="content-section">
        <legend class="border-bottom mb-4">Further developments</legend>
        <p>This website is still work in progress. We are planning to introduce several new features in the future, some
            of them being:
        <ul>
            <li>GARCH Dataset Creation</li>
            <li>Expectation-Maximization algorithm</li>
            <li>Diffuse initialization</li>
            <li>Model Identification</li>
            <li>Model Diagnostic Check</li>
            <li>Comparison with Machine Learning</li>
            <li>Discretization of continuous models</li>
            <li>Post export in tex and pdf format</li>
        </ul>
        </p>
    </div>
    <div class="content-section">
        <legend class="border-bottom mb-4">References</legend>
        <p>The main references for this thesis are:
            <ul>
                <li>
        <p><i class="fa fa-book mr-2"></i> Harvey: Forecasting, structural time series and the Kalman filter.
            (1990)</p></li>
        <li><p><i class="fa fa-book mr-2"></i> Hamilton: Time Series Analysis. (1994)</p></li>
        <li><p><i class="fa fa-book mr-2"></i> Durbin and Koopman: Time series analysis by state space methods.
            (2012)</p></li>
        </ul>
        </p>
    </div>
    <div class="content-section">
        <legend class="border-bottom mb-4">Contacts and links</legend>
        <p><i class="fa fa-envelope-o mr-2"></i>roberto.pizziol(at)gmail.com</p>
        <p><i class="fa fa-gitlab mr-2"></i><a href="https://gitlab.com/rpizziol">gitlab.com/rpizziol</a></p>
        <p><i class="fa fa-code mr-2"></i><a href="https://gitlab.com/rpizziol/sowa">gitlab.com/rpizziol/sowa</a></p>
    </div>
{% endblock content %}